name: mlp-v-oracle_fixed-D_no-nonlin_uniform
generators:
  - name: k8l8m10
    k: 8
    l: 8
    m: 10
datasets:
  - name: diag02
    display_name: diagonal ∆0.2
    n: 1024
    generative: true
    sample_kwargs:
      sample_mode: diagonal
      delta: 0.2
models:
  - name: oracle
    display_name: Oracle
    model: CompositionalMLP
    kwargs:
      D: 400
    train:
      bs: 64
      epochs: 10000
      lr: 0.1
      lr_steps: []
  - name: MLP
    display_name: MLP
    model: MLP
    kwargs:
      D: 400
    train:
      bs: 64
      epochs: 10000
      lr: 0.1
      lr_steps: []
  # - name: MLP0001ccn
  #   display_name: MLP compositional contrast λ=0.001 normalized
  #   model: MLP
  #   kwargs:
  #     D: 400
  #   train:
  #     bs: 64
  #     epochs: 10000
  #     lr: 0.1
  #     lr_steps: []
  #     regularizers:
  #       - function: comp_contrast
  #         weight: 0.001
  #         p: 2
  #         normalize: True