save_name: COOD
save_dir: /mnt/qb/work/bethge/twiedemer43/code/cood/_checkpoints
seed: 0
data:
  D: [2, 2]
  M: [16, 16]
  phi: InvertibleMLP
  phi_kwargs: {}
  C: LinearComposition
  C_kwargs: {}
model:
  phi: InvertibleMLP
  phi_kwargs:
  reuse_phi: False
train:
  epochs: 5000
  data:
    mode: random
    n_samples: 10000
    resample: True
    batch_size: 512
  loss: MSE
  loss_kwargs: {}
  optimizer: AdamW
  optimizer_kwargs:
    lr: 0.001
    weight_decay: 1e-5
  scheduler: CosineAnnealingLR
  # scheduler_kwargs:
    # T_max: 1000
    # eta_min: 1e-5
  use_cudnn_backend: True
wandb:
  watch: False
  watch_freq: 50
# eval:
#   freq: 100
#   metrics: [R2Score, MSE]
#   save_scores: []
#   data:
#     all:
#       mode: random
#       n_samples: 10000
#       resample: False
#       transform: scale_latents
#       batch_size: 1000
#     ID:
#       mode: orthogonal
#       n_samples: 10000
#       resample: False
#       transform: scale_latents
#       batch_size: 1000
# visualization:
#   freq: 100
#   data:
#     heatmap:
#       type: heatmap
#       mode: grid
#       n_samples: 10000
#       resample: False
#       transform: scale_latents
#       batch_size: 1000
#     reconstruction:
#       type: reconstruction
#       mode: random
#       n_samples: 10000
#       resample: False
#       transform: scale_latents
#       batch_size: 5