save_name: COOD
save_dir: /mnt/qb/work/bethge/twiedemer43/code/cood/_checkpoints
seed: 0
data:
  D: [2, 2]
  M: [16, 16]
  phi: InvertibleMLP
  phi_kwargs:
    d_hidden: 10
  C: LinearComposition
  C_kwargs: {}
model:
  phi: InvertibleMLP
  phi_kwargs:
    d_hidden: 10
train:
  epochs: 5000
  sample:
    mode: random
    n_samples: 10000
    resample: True
  batch_size: 512
  lr: 0.001
  scheduler: CosineAnnealingLR
  scheduler_kwargs:
    T_max: 1000
    eta_min: 1e-5
  optimizer: AdamW
  optimizer_kwargs: {}
  weight_decay: 1e-5
wandb:
  watch: False
  watch_freq: 50
eval:
  freq: 100
  sample:
    - name: all
      mode: random
      n_samples: 10000
      resample: False
      transform: scale_latents
    - name: ID
      mode: orthogonal
      n_samples: 10000
      resample: False
      transform: scale_latents
  batch_size: 1000
  metrics:
    - R2Score
    - MSE
  save_scores: []
visualization:
  heatmap:
    load: /mnt/qb/work/bethge/twiedemer43/data/cood/SW_eval_grid_1e4.pt
    mode: grid
    n_samples: 10000
    resample: False
    transform: scale_latents
    batch_size: 1000
  reconstruction:
    load: /mnt/qb/work/bethge/twiedemer43/data/cood/SW_eval_rand_1e4.pt
    mode: random
    n_samples: 10000
    resample: False
    transform: scale_latents
    batch_size: 5