datasets:
- display_name: "diagonal \u22060.2"
  generative: true
  n: 1024
  name: diag02
  sample_kwargs:
    delta: 0.2
    sample_mode: diagonal
generators:
- k: 8
  l: 8
  m: 10
  name: k8l8m10
models:
- display_name: Oracle
  load: /mnt/qb/work/bethge/twiedemer43/code/iood/res/mlp_vs_oracle/k8l8m10_diag02_oracle.pth
  model: CompositionalMLP
  name: oracle
  train:
    bs: 64
    epochs: 10000
    lr: 0.1
    lr_steps: []
- display_name: MLP
  model: MLP
  name: MLP
  train:
    bs: 64
    epochs: 10000
    lr: 0.1
    lr_steps: []
- display_name: "MLP compositional contrast \u03BB=0.001 normalized"
  model: MLP
  name: MLP0001ccn
  train:
    bs: 64
    epochs: 10000
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      normalize: true
      p: 2
      weight: 0.001
name: mlp_v_oracle
