datasets:
- display_name: "diagonal \u22060.2"
  generative: true
  n: 1024
  name: diag02
  sample_kwargs:
    delta: 0.2
    sample_mode: diagonal
generators:
- k: 8
  l: 2
  m: 10
  name: k8l2m10
- k: 12
  l: 2
  m: 10
  name: k12l2m10
- k: 8
  l: 3
  m: 10
  name: k8l3m10
models:
- display_name: MLP
  model: MLP
  name: MLP
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
- display_name: "MLP compositional contrast \u03BB=0.1"
  model: MLP
  name: MLP01cc
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      p: 2
      weight: 0.1
- display_name: "MLP compositional contrast \u03BB=0.1 normalized"
  model: MLP
  name: MLP01ccn
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      normalize: true
      p: 2
      weight: 0.1
name: testing_new_cc
