datasets:
- display_name: "diagonal \u22060.2"
  generative: true
  n: 1024
  name: diag02
  sample_kwargs:
    delta: 0.2
    sample_mode: diagonal
generators:
- k: 8
  l: 4
  m: 10
  name: k8l4m10
- k: 8
  l: 8
  m: 10
  name: k8l8m10
models:
- display_name: MLP
  model: MLP
  name: MLP
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
- display_name: "MLP compositional contrast \u03BB=0.1"
  model: MLP
  name: MLP01cc
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      p: 2
      weight: 0.1
- display_name: "MLP compositional contrast \u03BB=0.1 normalized"
  model: MLP
  name: MLP01ccn
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      normalize: true
      p: 2
      weight: 0.1
- display_name: "MLP compositional contrast \u03BB=0.01"
  model: MLP
  name: MLP001cc
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      p: 2
      weight: 0.01
- display_name: "MLP compositional contrast \u03BB=0.01 normalized"
  model: MLP
  name: MLP001ccn
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      normalize: true
      p: 2
      weight: 0.01
- display_name: "MLP compositional contrast \u03BB=0.001"
  model: MLP
  name: MLP0001cc
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      p: 2
      weight: 0.001
- display_name: "MLP compositional contrast \u03BB=0.001 normalized"
  model: MLP
  name: MLP0001ccn
  train:
    bs: 64
    epochs: 100
    lr: 0.1
    lr_steps: []
    regularizers:
    - function: comp_contrast
      normalize: true
      p: 2
      weight: 0.001
name: gs__reg_weights
